### ISSUE TITLE
Search bar not 'active' when loading the webpage.

### ISSUE THREAD

**Issue by ghost** [ubuntu-mate/start.ubuntu-mate.org#1]
When loading the start.ubuntu-mate.org webpage, the search bar is not automatically selected/active to begin typing. You must first click within the bounds of the search box to begin typing. I'm unaware if this is intentional, so I am filing the issue in the case that it's not.

**Comment by lah7** [comment]
Thanks, it was _kind of_ supposed to auto-focus, but now it will always be sure to focus now.
