### ISSUE TITLE
Add Restore Previous Session option on the start page

### ISSUE THREAD

**Issue by Neverest** [ubuntu-mate/start.ubuntu-mate.org#2]
Would be nice if the ubuntu mate start page also has the Restore Previous Session button like the regular firefox start page.

**Comment by lah7** [comment]
If it's technically possible to do this in Firefox (as it is a website after all), it would be a nice feature to incorporate. I had a look online but I couldn't work out how Firefox does this, or if it's purely internal to Firefox and impossible for a website to trigger the "restore last session" function.

**Comment by lah7** [comment]
3 years have passed - Firefox doesn't show a "restore last session" button on their start page any more.

    about:home

I don't believe it's possible for a web page to access browser-specific features due to security implications.
