### ISSUE TITLE
Different search engines for China

### ISSUE THREAD

**Issue by ucSec** [ubuntu-mate/start.ubuntu-mate.org#4]
In https://start.ubuntu-mate.org/ , the website provide two search engine. Google and Duckduckgo, but in China, we cannot connect these two. We use Baidu, Sogou, and Bing is also OK for us.

Maybe it is not an important question, but it is still a question. And probably only me look it so serious......

[Baidu](baidu.com)

[Sogou](sogou.com)

[Bing](bing.com)

Thx!

**Comment by lah7** [comment]
Thanks for letting us know, apologies for not responding sooner.

We'll need to restructure the page in #5 in order to support more search engines.
