### ISSUE TITLE
Very slow in China

### ISSUE THREAD

**Issue by ucSec** [ubuntu-mate/start.ubuntu-mate.org#7]
### Details about the problem
I found that it is very slow to get start.ubuntu-mate.org in China.
Because of GFW, it is Google analytics.js let the load speed down.
### Screenshots
<img width="1412" alt="截屏2020-04-05 上午8 01 21" src="https://user-images.githubusercontent.com/47733616/78463792-aa17ec80-7713-11ea-9749-41168acca264.png">
### Link(s) to the affected pages
https://www.google-analytics.com/analytics.js
### Environment

- **Browser:** Chrome 80/Firefox 74.0/etc
- **OS:** Ubuntu MATE 20.04/Android 10/etc

**Comment by lah7** [comment]
Our CDN, **CloudFlare**, was causing this - a feature named **Rocket Launcher** was enabled and added the Google Analytics requests which has now been disabled.

Please try again and confirm if the speed is much better now?

There should only be 2 requests: `/` and `/favicon.ico`.

**Comment by ucSec** [comment]
Wow, thank you so much, it is much faster than before!
